### PR TITLE
handle gh/e resp with no link header

### PR DESCRIPTION
**Pull request by dgreisen-cfpb**

### CODE REVIEW

**Comment by m3brown** [comment]
Can't this be done a lot cleaner?
```python
if links and next_re.match(links):
    return next_match.groups()[0]
else:
    return None
```

**Comment by dgreisen-cfpb** [comment]
no because if links is None, then it will error.

**Comment by dgreisen-cfpb** [comment]
ok. could default to empty string.

**Comment by m3brown** [comment]
Ok I'll merge it, not worth fretting over.

**Pull request merged**
