### PR TITLE
Change path to path_analyzed in ES query

### PR DESCRIPTION
**Pull request by dpford**
Previously, the ES query being generated was filtering by "path", but the correct field is "path_full".  This makes that change.

### CODE REVIEW

**Comment by dgreisen-cfpb** [comment]
shouldn't it be path_analyzed, not path_full, to get the tree functionality?

**Comment by dgreisen-cfpb** [comment]
actually, I think it should be `path.path_analyzed`. See: https://github.com/cfpb/github-wiki-search/blob/fb2dc1ae13353bc4009bac261fd1b4180fadc4cb/client/src/static/js/app.js

**Comment by dpford** [comment]
Ah, good call.  path_full works for when the full path is entered.  path_analyzed works for both the full path and the first part of it (e.g. /cfpb).  I didn't see a difference between path.path_analyzed and just path_analyzed.

**Comment by dgreisen-cfpb** [comment]
looks good.

**Pull request merged**
